# Generated by Django 4.2.4 on 2023-08-22 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/uploads/images/%Y/%m', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=255, verbose_name='Атрибут alt')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Порядок сортировки')),
                ('supplier_url', models.URLField(blank=True, verbose_name='URL')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
    ]
