# Generated by Django 4.2.4 on 2023-08-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
