# Generated by Django 4.2.4 on 2023-08-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_currency_manufacturer_alter_product_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Валюта', 'verbose_name_plural': 'Валют'},
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_sign',
            field=models.CharField(default=0, max_length=255, verbose_name='Знак валюты'),
            preserve_default=False,
        ),
    ]
