# Generated by Django 4.2.4 on 2023-08-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_currency_options_alter_manufacturer_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюта'},
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/images/%Y/%m', verbose_name='Изображение'),
        ),
    ]
