# Generated by Django 4.2.4 on 2023-08-27 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='main_image',
            field=models.BooleanField(blank=True, null=True, verbose_name='Выберите гланое фото'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gallery_images', to='catalog.product'),
        ),
    ]
