# Generated by Django 4.2.4 on 2023-08-28 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_gallery_main_image_alter_gallery_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gallery_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='main_img', to='catalog.gallery'),
        ),
    ]
