# Generated by Django 4.2.4 on 2023-08-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_gallery_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gallery_img',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='main_image',
            field=models.BooleanField(default=False, verbose_name='Выберите гланое изображение'),
        ),
    ]
