# Generated by Django 4.2.4 on 2023-10-31 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_remove_product_gallery_img_alter_gallery_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=255, unique=True, verbose_name='Тег')),
                ('slug', models.SlugField(max_length=155, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Теги для поиска',
                'verbose_name_plural': 'Теги для поиска',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='barcode',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='search_tag',
            field=models.ManyToManyField(default=models.CharField(max_length=200, unique=True, verbose_name='Название категории товара'), to='catalog.searchtag'),
        ),
    ]
