# Generated by Django 4.2.4 on 2023-10-31 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_searchtag_remove_product_barcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='search_tag',
        ),
        migrations.DeleteModel(
            name='SearchTag',
        ),
    ]
