# Generated by Django 4.2.4 on 2023-11-08 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_tagproduct_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2023, 11, 8, 0, 15, 25, 678221, tzinfo=datetime.timezone.utc), max_length=200, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
