# Generated by Django 4.2.4 on 2023-11-26 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_remove_product_tags_productcategory_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='tags',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='catalog.tagproduct'),
        ),
    ]
