# Generated by Django 4.2.4 on 2023-09-02 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_paid_order_postal_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
