# Generated by Django 4.2.4 on 2023-09-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='consent',
            field=models.BooleanField(default=True, verbose_name='Согласие с политикой конфиденциальности'),
        ),
    ]
