# Generated by Django 4.2.4 on 2023-09-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callorderform',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='callorderform',
            name='phone',
            field=models.CharField(verbose_name='Телефон', max_length=200),
        ),
    ]
