# Generated by Django 4.2.4 on 2023-09-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_sendmessageform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessageform',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
