# Generated by Django 4.2.4 on 2023-11-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_sendmessageform_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callorderform',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='sendmessageform',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Телефон'),
        ),
    ]
