# Generated by Django 4.2.4 on 2023-09-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(upload_to='static/app/images/bunner', verbose_name='Изображение')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка')),
            ],
        ),
    ]
