# Generated by Django 4.2.4 on 2023-09-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_banner_options_banner_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='alt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Alt'),
        ),
    ]
